Remove imports without "only"
dftbplus/dftbplus pull request #1382
Opened 2024-02-01 13:48 UTC by jubich

I have noticed that the following import is not reached even if it is compiled with the "WITH_MPI" flag.

https://github.com/dftbplus/dftbplus/blob/13588bb08d666d3beadc579e345dec6683fa9145/app/misc/skderivs/skderivs.F90#L24-L26

2024-02-06 10:26 UTC, aradi requested changes
Please, make sure, that you align with our style guide everywhere. I see several continuation lines with incorrect indentation (should be 4 characters). Also, you can use line lengths up to 100 characters.

2024-04-09 16:03 UTC, aradi approved these changes

2024-04-09 16:04 UTC, aradi commented
Perfect, could you please re-base it to current main, and then we can merge it. (Sorry for taking so long...)

2024-10-31 15:18 UTC, jubich commented
.

2024-12-18 20:34 UTC, merged