Analytical gamma second derivative
dftbplus/dftbplus pull request #1443
Opened 2024-04-20 00:21 UTC by bhourahine

Replace finite difference for global hybrids.

2024-04-20 08:40 UTC, vanderhe commented
@bhourahine Did you already check that the new routines reproduce the old ones? This is not necessarily caught by the regression tests.

2024-04-20 08:46 UTC, vanderhe requested changes

2024-04-20 08:46 UTC, vanderhe commented on src/dftbp/dftb/rshgamma.F90
> +            & (2.0_dp*tauA**3/48.0_dp + 2.0_dp/dist**3 - tauA*(2.0_dp*dist*tauA**3/48.0_dp&
Style guide violations in most lines ;)
```suggestion
            & (2.0_dp * tauA**3 / 48.0_dp + 2.0_dp / dist**3 - tauA * (2.0_dp * dist * tauA**3 / 48.0_dp&
```
+induced line breaks, if applicable

2024-04-20 09:20 UTC, bhourahine commented
> @bhourahine Did you already check that the new routines reproduce the old ones? This is not necessarily caught by the regression tests.

getddYGammaSubPart was explicity tested, but not the full term. If there is no coverage, how was the original expression tested? And any reason why a test can't be added?

2024-04-20 09:24 UTC, vanderhe commented
> > @bhourahine Did you already check that the new routines reproduce the old ones? This is not necessarily caught by the regression tests.
> 
> getddYGammaSubPart was explicity tested, but not the full term. If there is no coverage, how was the original expression tested? And any reason why a test can't be added?

Back then I verified that the 5-th order polynomial smoothly connects and plotted the whole thing. Although there is at least one test with the damped TCI, I'm not sure if it really hits the damped region.

2024-06-09 16:41 UTC, vanderhe commented
@bhourahine I have now systematically checked the second derivatives, let's discuss next devel. meeting.

2025-03-20 12:52 UTC, bhourahine commented
@aradi as the 2nd derivative is used in the polynomial tail, this might have a slight effect, will try and test more carefully.

2025-03-31 18:52 UTC, merged